# Generated by Django 3.0.1 on 2019-12-21 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_movrotativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movrotativo',
            name='checkin',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='movrotativo',
            name='checkout',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
