# Generated by Django 3.0.1 on 2020-01-10 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='mensagem',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
